---
  - block:
     - apt: name={{ apache.debian.package }} state=present update_cache=true
     - service: name=apache2 state=started
    when: ansible_os_family == "Debian"
    become: yes

  - block:
     - yum: name={{ apache.redhat.package }} state=present
     - service: name=httpd state=started
    when: ansible_os_family == "RedHat"
    become: yes
