---
  - block:
     - apt: name=software-properties-common state=present update_cache=true
     - apt_repository: repo={{ debian.java_repo }}
     - debconf: name='oracle-{{ debian.java_version}}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
     - apt: name=oracle-{{ debian.java_version}}-installer state=present update_cache=true
     - shell: /usr/bin/java -version 2>&1 | head -1 | awk -F'"' '{print $2}'
       register: java_version
     - debug: var=java_version.stdout
    when: ansible_os_family == "Debian"
    become: yes

  - block:
     - yum: name=python-httplib2 state=present
     - uri: url={{ redhat.jdk_url }} HEADER_Cookie="gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" dest=/tmp/
     - unarchive: src=/tmp/{{ redhat.jdk_version }}.tar.gz dest=/opt/ copy=no
     - shell: update-alternatives --install /usr/bin/java java {{ redhat.jdk_path }}/bin/java 1
     - shell: /usr/bin/java -version 2>&1 | head -1 | awk -F'"' '{print $2}'
       register: java_version
     - debug: var=java_version.stdout
    when: ansible_os_family == "RedHat"
    become: yes
