---
  - name: Installation of Jenkins
    hosts: jenkins_host
    roles:
      - { role: ../roles/java }
    tasks:
      - block:
         - apt: name=software-properties-common state=present update_cache=true
         - apt_key: url={{ debian.jenkins_apt_key }} state=present
         - apt_repository: repo={{ debian.jenkins_apt_repo }} state=present
         - apt: name=jenkins state=present update_cache=true
         - service: name=jenkins state=started
        when: ansible_os_family == "Debian"
        become: yes
    
      - block:
         - get_url: url={{ redhat.jenkins_rpm_repo }} dest=/etc/yum.repos.d/jenkins.repo
         - rpm_key: key={{ redhat.jenkins_rpm_key }} state=present
         - yum: name=jenkins state=present
         - service: name=jenkins state=started
        when: ansible_os_family == "RedHat"
        become: yes
